// BEGIN GENERATED SPORTS RULES
// Generated by tools/sync-sports-server.mjs; edit assets/sports rules, then sync.
const {PADS, PP_PADS, newRound, currentPlayer, playShot, advanceRound} = (() => {
// Three coastal park parcels from the user screenshots; roads are preserved.
const REGIONS = [
  {
    "x": -1227.5759188948698,
    "z": 2997.82479196178,
    "w": 290.3377090966211,
    "d": 243.9479325048952,
    "rot": -0.5840922061493135,
    "use": "park",
    "i": -4,
    "j": 8,
    "D": 900,
    "poly": [
      [
        -1186.7312247986367,
        3232.9301520196277
      ],
      [
        -1384.0451916844313,
        3154.665810202444
      ],
      [
        -1428.5949452235186,
        3128.5702546477332
      ],
      [
        -1452.5999233098905,
        2956.071275110796
      ],
      [
        -1098.1227237628702,
        2721.750158101443
      ],
      [
        -1024.3946874772928,
        3034.100672792074
      ]
    ],
    "y": 3.049762640263061,
    "shore": false
  },
  {
    "x": -905.4599694187386,
    "z": 2856.282003390044,
    "w": 217.38580559901308,
    "d": 189.78354920562418,
    "rot": -1.8025961195889781,
    "use": "park",
    "i": -3,
    "j": 8,
    "D": 900,
    "poly": [
      [
        -791.2403770604246,
        3051.8109605346112
      ],
      [
        -1010.9398220511338,
        3021.0684770145767
      ],
      [
        -1085.8399787882668,
        2703.7522471799175
      ],
      [
        -1078.3843369299816,
        2671.218457252272
      ],
      [
        -1056.5533743456765,
        2655.417529943966
      ],
      [
        -865.3784644496872,
        2694.5274716300883
      ],
      [
        -701.4667635550787,
        2845.6787459310012
      ]
    ],
    "y": 2.991603171498073,
    "shore": false
  },
  {
    "x": -652.1163522854876,
    "z": 2686.390010814389,
    "w": 187.9882976653511,
    "d": 143.14935782270763,
    "rot": -0.5509656667389495,
    "use": "park",
    "i": -2,
    "j": 7,
    "D": 900,
    "poly": [
      [
        -525.1555615288966,
        2786.2987364751725
      ],
      [
        -694.9912004030995,
        2839.437898656449
      ],
      [
        -856.3273478918494,
        2690.6616724893847
      ],
      [
        -544.0526719610015,
        2498.7892882369983
      ],
      [
        -532.2620458430528,
        2501.1903925155907
      ]
    ],
    "y": 2.9226094292571863,
    "shore": false
  }
];
const HOLES = [
  {
    "id": 1,
    "region": 0,
    "par": 4,
    "tee": [
      -1341.3344272163633,
      3.2497626402630613,
      2988.9496305188436
    ],
    "cup": [
      -1191.1682580094655,
      3.2497626402630613,
      2889.6848412727636
    ],
    "width": 13,
    "bunker": [
      -1230.4601449653755,
      2925.0157964247055,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 2,
    "region": 0,
    "par": 4,
    "tee": [
      -1175.6980885222476,
      3.2497626402630613,
      2913.0878636991542
    ],
    "cup": [
      -1324.4721896025167,
      3.2497626402630613,
      3014.4585511135433
    ],
    "width": 13,
    "bunker": [
      -1277.9628851455664,
      2990.0459885349364,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 3,
    "region": 0,
    "par": 4,
    "tee": [
      -1310.3940882419276,
      3.2497626402630613,
      3035.755675371625
    ],
    "cup": [
      -1158.7236437975437,
      3.2497626402630613,
      2938.7665293980663
    ],
    "width": 13,
    "bunker": [
      -1199.5198059909399,
      2971.8218412774863,
      4.5,
      3
    ],
    "water": [
      -1239.3467000264486,
      2980.0181444634395,
      5,
      3
    ]
  },
  {
    "id": 4,
    "region": 0,
    "par": 4,
    "tee": [
      -1144.757749547812,
      3.2497626402630613,
      2959.8939085519355
    ],
    "cup": [
      -1294.6904601223903,
      3.2497626402630613,
      3059.51187024466
    ],
    "width": 13,
    "bunker": [
      -1247.0225461711307,
      3036.8520333877173,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 5,
    "region": 0,
    "par": 4,
    "tee": [
      -1279.453749267492,
      3.2497626402630613,
      3082.561720224406
    ],
    "cup": [
      -1130.5395788233463,
      3.2497626402630613,
      2981.402927480387
    ],
    "width": 13,
    "bunker": [
      -1168.5794670165042,
      3018.6278861302676,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 6,
    "region": 0,
    "par": 4,
    "tee": [
      -1113.8174105733763,
      3.2497626402630613,
      3006.699953404717
    ],
    "cup": [
      -1265.5699540495116,
      3.2497626402630613,
      3103.5649012896342
    ],
    "width": 13,
    "bunker": [
      -1216.082207196695,
      3083.6580782404985,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 7,
    "region": 1,
    "par": 3,
    "tee": [
      -943.0820490672746,
      3.1916031714980733,
      2934.4039157374145
    ],
    "cup": [
      -974.0448140611005,
      3.1916031714980733,
      2803.229452543981
    ],
    "width": 13,
    "bunker": [
      -959.1449780027768,
      2839.917196746883,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 8,
    "region": 1,
    "par": 3,
    "tee": [
      -952.8034292029209,
      3.1916031714980733,
      2798.2155802437196
    ],
    "cup": [
      -919.3837679263316,
      3.1916031714980733,
      2928.810111182311
    ],
    "width": 13,
    "bunker": [
      -924.9192078246057,
      2889.911970301932,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 9,
    "region": 1,
    "par": 3,
    "tee": [
      -900.5992793509155,
      3.1916031714980733,
      2924.3761711368916
    ],
    "cup": [
      -928.9071108910296,
      3.1916031714980733,
      2792.5750304743815
    ],
    "width": 13,
    "bunker": [
      -916.6622082864177,
      2829.88945214636,
      4.5,
      3
    ],
    "water": [
      -921.621892680397,
      2860.0969062271993,
      5,
      3
    ]
  },
  {
    "id": 10,
    "region": 1,
    "par": 3,
    "tee": [
      -910.3206594865618,
      3.1916031714980733,
      2788.187835643196
    ],
    "cup": [
      -878.9458574415654,
      3.1916031714980733,
      2919.265040528316
    ],
    "width": 13,
    "bunker": [
      -882.4364381082465,
      2879.8842257014085,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 11,
    "region": 1,
    "par": 3,
    "tee": [
      -858.1165096345563,
      3.1916031714980733,
      2914.348426536368
    ],
    "cup": [
      -891.2889589443929,
      3.1916031714980733,
      2783.695543035518
    ],
    "width": 13,
    "bunker": [
      -874.1794385700586,
      2819.8617075458365,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 12,
    "region": 1,
    "par": 3,
    "tee": [
      -867.8378897702027,
      3.1916031714980733,
      2778.1600910426732
    ],
    "cup": [
      -839.6749568899098,
      3.1916031714980733,
      2909.9954339656138
    ],
    "width": 13,
    "bunker": [
      -839.9536683918874,
      2869.8564811008855,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 13,
    "region": 2,
    "par": 3,
    "tee": [
      -723.3142454881163,
      3.1226094292571864,
      2681.833055518536
    ],
    "cup": [
      -624.0090479908627,
      3.1226094292571864,
      2620.8165002834535
    ],
    "width": 11.45194862581661,
    "bunker": [
      -650.441504251819,
      2642.433896942176,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 14,
    "region": 2,
    "par": 3,
    "tee": [
      -615.3909302092619,
      3.1226094292571864,
      2634.8425934488114
    ],
    "cup": [
      -713.3745716757148,
      3.1226094292571864,
      2698.009997451687
    ],
    "width": 11.45194862581661,
    "bunker": [
      -683.4675015497118,
      2682.047577786762,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 15,
    "region": 2,
    "par": 3,
    "tee": [
      -706.0780099249148,
      3.1226094292571864,
      2709.8852418492515
    ],
    "cup": [
      -605.34473288611,
      3.1226094292571864,
      2651.192903711793
    ],
    "width": 11.45194862581661,
    "bunker": [
      -633.2052686886175,
      2670.4860832728914,
      4.5,
      3
    ],
    "water": [
      -658.6736158149664,
      2675.717983405965,
      5,
      3
    ]
  },
  {
    "id": 16,
    "region": 2,
    "par": 3,
    "tee": [
      -598.1546946460603,
      3.1226094292571864,
      2662.8947797795263
    ],
    "cup": [
      -697.2382588355883,
      3.1226094292571864,
      2724.272045961185
    ],
    "width": 11.45194862581661,
    "bunker": [
      -666.2312659865103,
      2710.0997641174768,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 17,
    "region": 2,
    "par": 3,
    "tee": [
      -688.8417743617132,
      3.1226094292571864,
      2737.9374281799664
    ],
    "cup": [
      -590.7251584315679,
      3.1226094292571864,
      2674.9864417596336
    ],
    "width": 11.45194862581661,
    "bunker": [
      -615.969033125416,
      2698.5382696036063,
      4.5,
      3
    ],
    "water": null
  },
  {
    "id": 18,
    "region": 2,
    "par": 3,
    "tee": [
      -580.9184590828588,
      3.1226094292571864,
      2690.9469661102416
    ],
    "cup": [
      -681.7296766106801,
      3.1226094292571864,
      2749.51245513888
    ],
    "width": 11.45194862581661,
    "bunker": [
      -648.9950304233087,
      2738.151950448192,
      4.5,
      3
    ],
    "water": null
  }
];
const PADS = [
  {
    "id": "golf-single-3",
    "mode": "single",
    "holes": 3,
    "slots": [
      [
        -1387.954743504955,
        3.349762640263061,
        2986.868954291469
      ]
    ]
  },
  {
    "id": "golf-single-9",
    "mode": "single",
    "holes": 9,
    "slots": [
      [
        -1374.502422211722,
        3.349762640263061,
        3007.2194085752867
      ]
    ]
  },
  {
    "id": "golf-single-18",
    "mode": "single",
    "holes": 18,
    "slots": [
      [
        -1361.050100918489,
        3.349762640263061,
        3027.5698628591044
      ]
    ]
  },
  {
    "id": "golf-duel-3",
    "mode": "duel",
    "holes": 3,
    "slots": [
      [
        -1347.5977796252562,
        3.349762640263061,
        3047.9203171429226
      ],
      [
        -1344.9282979436719,
        3.349762640263061,
        3046.1557017310874
      ]
    ]
  },
  {
    "id": "golf-duel-9",
    "mode": "duel",
    "holes": 9,
    "slots": [
      [
        -1334.1454583320233,
        3.349762640263061,
        3068.2707714267403
      ],
      [
        -1331.475976650439,
        3.349762640263061,
        3066.506156014905
      ]
    ]
  },
  {
    "id": "golf-duel-18",
    "mode": "duel",
    "holes": 18,
    "slots": [
      [
        -1320.6931370387904,
        3.349762640263061,
        3088.621225710558
      ],
      [
        -1318.023655357206,
        3.349762640263061,
        3086.856610298723
      ]
    ]
  },
  {
    "id": "golf-teams-3",
    "mode": "teams",
    "holes": 3,
    "slots": [
      [
        -1307.2408157455575,
        3.349762640263061,
        3108.9716799943762
      ],
      [
        -1304.5713340639732,
        3.349762640263061,
        3107.207064582541
      ],
      [
        -1301.9018523823888,
        3.349762640263061,
        3105.442449170706
      ],
      [
        -1299.2323707008047,
        3.349762640263061,
        3103.6778337588707
      ]
    ]
  },
  {
    "id": "golf-teams-9",
    "mode": "teams",
    "holes": 9,
    "slots": [
      [
        -1293.7884944523246,
        3.349762640263061,
        3129.322134278194
      ],
      [
        -1291.1190127707403,
        3.349762640263061,
        3127.557518866359
      ],
      [
        -1288.449531089156,
        3.349762640263061,
        3125.7929034545236
      ],
      [
        -1285.7800494075718,
        3.349762640263061,
        3124.0282880426885
      ]
    ]
  },
  {
    "id": "golf-teams-18",
    "mode": "teams",
    "holes": 18,
    "slots": [
      [
        -1280.3361731590915,
        3.349762640263061,
        3149.6725885620117
      ],
      [
        -1277.6666914775071,
        3.349762640263061,
        3147.9079731501765
      ],
      [
        -1274.9972097959228,
        3.349762640263061,
        3146.1433577383414
      ],
      [
        -1272.3277281143387,
        3.349762640263061,
        3144.378742326506
      ]
    ]
  }
];

const CLUBS = [{name:'드라이버',range:210,loft:.48},{name:'아이언',range:110,loft:.68},{name:'웨지',range:45,loft:.95},{name:'퍼터',range:18,loft:0}];
const MAX_STROKES=12;
function inside(x,z,poly){let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>z)!==(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
const ellipse=(x,z,e)=>e&&((x-e[0])/e[2])**2+((z-e[1])/e[3])**2<1;
function lieAt(h,p){if(!inside(p[0],p[2],REGIONS[h.region].poly))return 'OB';if(ellipse(p[0],p[2],h.water))return '물';if(Math.hypot(p[0]-h.cup[0],p[2]-h.cup[2])<7)return '그린';if(ellipse(p[0],p[2],h.bunker))return '벙커';const dx=h.cup[0]-h.tee[0],dz=h.cup[2]-h.tee[2],len=Math.hypot(dx,dz),t=((p[0]-h.tee[0])*dx+(p[2]-h.tee[2])*dz)/(len*len);return t>=-.1&&t<=1.1&&Math.abs((p[0]-h.tee[0])*dz-(p[2]-h.tee[2])*dx)/len<h.width/2?'페어웨이':'러프';}
// Identical fixed-step ball flight, bounce, rolling friction and cup detection on server and browser.
function simulateShot(h,start,input){
 const club=CLUBS[input.club],power=Math.max(.01,Math.min(1,input.power)),angle=input.angle+input.error*.15,putt=club.loft===0,lie=lieAt(h,start),factor=lie==='벙커'?.55:lie==='러프'?.8:1;
 const distance=club.range*power*factor,speed=putt?Math.sqrt(2*1.4*distance):Math.sqrt(distance*9.81/Math.sin(2*club.loft)),p=start.slice(),v=[Math.cos(angle)*speed*Math.cos(club.loft),speed*Math.sin(club.loft),Math.sin(angle)*speed*Math.cos(club.loft)],frames=[[0,...p]];
 let cup=false,penalty=false,time=0,bounced=putt;
 for(let k=1;k<=1800;k++){
  const prev=p.slice(),dt=1/60;time=k*dt;p[0]+=v[0]*dt;p[2]+=v[2]*dt;p[1]+=v[1]*dt;v[1]-=9.81*dt;
  if(p[1]<=h.tee[1]){p[1]=h.tee[1];const surface=lieAt(h,p),sp=Math.hypot(v[0],v[2]);
   if(surface==='OB'||surface==='물'){penalty=true;break;}
   const dx=p[0]-prev[0],dz=p[2]-prev[2],l=dx*dx+dz*dz,t=l?Math.max(0,Math.min(1,((h.cup[0]-prev[0])*dx+(h.cup[2]-prev[2])*dz)/l)):0;
   if(sp<3.2&&Math.hypot(prev[0]+t*dx-h.cup[0],prev[2]+t*dz-h.cup[2])<.45){p.splice(0,3,...h.cup);cup=true;break;}
   if(!putt&&!bounced&&Math.abs(v[1])>2){v[1]=Math.abs(v[1])*.24;v[0]*=.7;v[2]*=.7;bounced=true;}else{v[1]=0;const drag=surface==='그린'?1.4:surface==='벙커'?7:surface==='러프'?4:2.4;const f=Math.max(0,sp-drag*dt)/(sp||1);v[0]*=f;v[2]*=f;if(sp<.08)break;}
  }
  if(k%6===0)frames.push([time,...p]);
 }
 frames.push([time,...p]);return {frames,duration:time,end:penalty?start.slice():p,cup,penalty,lie:penalty?'벌타 후 재타격':lieAt(h,p)};
}
function newRound(ids,count,mode){const teams=mode==='teams'?[[ids[0],ids[1]],[ids[2],ids[3]]]:ids.map(id=>[id]);return {count,mode,teams,hole:0,turn:0,playerTurns:teams.map(()=>0),balls:teams.map(()=>HOLES[0].tee.slice()),strokes:teams.map(()=>0),done:teams.map(()=>false),scores:teams.map(()=>[]),phase:'play',shot:null,seq:0,winner:null};}
function currentPlayer(r){const team=r.teams[r.turn];return team[r.playerTurns[r.turn]%team.length];}
function playShot(r,input,time){if(r.phase!=='play')return false;const i=r.turn,h=HOLES[r.hole],result=simulateShot(h,r.balls[i],input);r.strokes[i]+=1+(result.penalty?1:0);r.strokes[i]=Math.min(MAX_STROKES,r.strokes[i]);r.shot={input,start:r.balls[i].slice(),team:i,hole:r.hole,at:time,duration:result.duration,penalty:result.penalty,cup:result.cup,seq:++r.seq};r.balls[i]=result.end;r.done[i]=result.cup||r.strokes[i]>=MAX_STROKES;r.playerTurns[i]++;r.phase='flight';return true;}
function advanceRound(r,time){if(r.phase!=='flight'||time<r.shot.at+r.shot.duration*1000)return false;
 if(r.done.every(Boolean)){r.scores.forEach((sc,i)=>sc.push(r.strokes[i]));r.hole++;if(r.hole>=r.count){r.phase='over';r.completed=true;const sums=r.scores.map(sc=>sc.reduce((a,b)=>a+b,0)),min=Math.min(...sums);r.winner=sums.filter(s=>s===min).length===1?sums.indexOf(min):-1;return true;}r.balls=r.teams.map(()=>HOLES[r.hole].tee.slice());r.strokes=r.teams.map(()=>0);r.done=r.teams.map(()=>false);r.turn=r.hole%r.teams.length;}
 else{for(let n=1;n<=r.teams.length;n++){const i=(r.turn+n)%r.teams.length;if(!r.done[i]){r.turn=i;break;}}}
 r.phase='play';r.deadline=time+60000;return true;}

const PP_PADS = [[[-2925.6493330742524,3.5045294134080973,-2542.79191502278],[-2920.9590914800124,3.5045294134080973,-2542.489204290126]],[[-2909.682553178968,3.5045294134080973,-2541.761410400979],[-2904.9923115847287,3.5045294134080973,-2541.4586996683247]]];
return {PADS, PP_PADS, newRound, currentPlayer, playShot, advanceRound};
})();
// END GENERATED SPORTS RULES
import { Basketball } from './basketball.js';
export class Sports {
 constructor(rooms,send,broadcast){this.rooms=rooms;this.send=send;this.broadcast=broadcast;this.states=new Map();this.basket=new Basketball(this);}
 state(room){if(!this.states.has(room))this.states.set(room,{pads:PADS.map(p=>({id:p.id,seats:p.slots.map(()=>null),phase:'wait',startAt:0,round:null})),pp:PP_PADS.map(()=>({seats:[null,null],busy:false}))});return this.states.get(room);}
 snapshot(room){const s=this.state(room);return {t:'golf',k:'state',serverNow:Date.now(),pads:s.pads};}
 publish(room){const peers=this.rooms.get(room);if(peers)this.broadcast(peers,this.snapshot(room));}
 protected(peer){const s=this.states.get(peer.roomId);return this.basket.protected(peer)||!!s&&(s.pads.some(p=>p.seats.includes(peer.id))||s.pp.some(p=>p.seats.includes(peer.id)));}
 near(peer,p,r=1.6){return peer.ready&&!(peer.s[7]&(16|128))&&!peer.s[4]&&Math.hypot(peer.s[0]-p[0],peer.s[2]-p[2])<=r&&Math.abs(peer.s[1]-p[1])<2;}
 receive(peer,m){const s=this.state(peer.roomId);if(m.k==='sync'){this.send(peer.ws,this.snapshot(peer.roomId));return;}
  const p=s.pads.find(p=>p.id===m.pad),spec=PADS.find(p=>p.id===m.pad);if(!p)return;
  if(m.k==='claim'){
   const slot=m.slot;if(!Number.isInteger(slot)||!spec.slots[slot]||p.phase!=='wait'||p.seats[slot]!==null||this.protected(peer)||!this.near(peer,spec.slots[slot])){this.send(peer.ws,{t:'golf',k:'denied',message:'다른 사람이 사용 중이거나 발판에서 벗어났습니다.'});return;}
   p.seats[slot]=peer.id;if(p.seats.every(id=>id!==null)){p.phase='count';p.startAt=Date.now()+5000;}this.publish(peer.roomId);
  }else if(m.k==='leave'&&p.seats.includes(peer.id)){this.leaveGolf(peer,p,m.forfeit!==false);}
  else if(m.k==='shot'&&p.phase==='play'&&p.round.phase==='play'&&currentPlayer(p.round)===peer.id&&m.seq===p.round.seq){
   const a=m.input;if(!a||!Number.isInteger(a.club)||a.club<0||a.club>3||![a.angle,a.power,a.error].every(Number.isFinite)||a.power<.01||a.power>1||Math.abs(a.angle)>Math.PI*4||Math.abs(a.error)>1)return;
   playShot(p.round,a,Date.now());this.publish(peer.roomId);
  }
 }
 leaveGolf(peer,p,forfeit){if(p.phase==='play'){const r=p.round;r.phase='over';r.winner=r.teams.length>1?1-r.teams.findIndex(t=>t.includes(peer.id)):null;r.reason=forfeit?'기권패':'연결 종료로 기권패';p.phase='over';p.endAt=Date.now()+5000;}
  else if(p.phase==='over'){p.seats=p.seats.map(id=>id===peer.id?null:id);if(p.seats.every(id=>id===null)){p.phase='wait';p.round=null;}}
  else{p.seats=p.seats.map(id=>id===peer.id?null:id);p.phase='wait';p.startAt=0;p.round=null;}this.publish(peer.roomId);}
 pp(peer,m){const s=this.state(peer.roomId),tb=m.tb,side=m.side;if(!Number.isInteger(tb)||tb<0||tb>1||![0,1].includes(side))return null;const table=s.pp[tb],room=this.rooms.get(peer.roomId);
  if(m.k==='sit'){if(table.seats[side]!==peer.id){if(table.busy||table.seats[side]!==null||this.protected(peer)||!this.near(peer,PP_PADS[tb][side],1.6)){this.send(peer.ws,{t:'pp',k:'denied',tb,side});return null;}table.seats[side]=peer.id;}
   if(table.seats.every(id=>id!==null)&&!table.startAt){table.startAt=Date.now()+5000;table.busy=true;}
   if(m.busy)table.busy=true;return {t:'pp',k:'sit',tb,side,id:peer.id,busy:table.busy?1:0,seats:table.seats,startAt:table.startAt||0};}
  if(table.seats[side]!==peer.id&&!(table.busy&&table.seats.includes(peer.id)&&table.seats[side]===null&&['shot','point'].includes(m.k)))return null;
  if(['shot','point'].includes(m.k)&&table.startAt&&Date.now()<table.startAt)return null;
  if(m.k==='stand'){table.seats[side]=null;table.busy=false;table.startAt=0;return {t:'pp',k:'stand',tb,side,id:peer.id};}
  if(!table.busy||!['pad','shot','point','end'].includes(m.k))return null;
  if(m.k==='end'){table.busy=false;table.startAt=0;}return {t:'pp',k:m.k,tb,side,id:peer.id,...(m.k==='end'&&m.forfeit?{forfeit:true,winner:1-side}:{})};
 }
 tick(time=Date.now()){
  this.basket.tick(time);
  for(const [room,s]of this.states){const peers=this.rooms.get(room);if(!peers){this.states.delete(room);continue;}let changed=false;
   s.pads.forEach((p,i)=>{if(p.phase==='wait'||p.phase==='count'){p.seats.forEach((id,j)=>{if(id!==null&&(!peers.has(id)||!this.near(peers.get(id),PADS[i].slots[j],2.2))){p.seats[j]=null;p.phase='wait';p.startAt=0;changed=true;}});if(p.phase==='count'&&time>=p.startAt){p.round=newRound(p.seats,PADS[i].holes,PADS[i].mode);p.round.deadline=time+60000;p.phase='play';changed=true;}}
    else if(p.phase==='play'){if(advanceRound(p.round,time)){changed=true;if(p.round.phase==='over'){p.phase='over';p.endAt=time+7000;}}else if(p.round.phase==='play'&&time>p.round.deadline){playShot(p.round,{club:3,power:.01,angle:0,error:0},time);changed=true;}}
    else if(p.phase==='over'&&time>=p.endAt){p.seats=p.seats.map(()=>null);p.phase='wait';p.round=null;changed=true;}});
   s.pp.forEach((p,tb)=>{if(!p.busy)p.seats.forEach((id,side)=>{if(id!==null&&(!peers.has(id)||!this.near(peers.get(id),PP_PADS[tb][side],1.8))){p.seats[side]=null;this.broadcast(peers,{t:'pp',k:'stand',tb,side,id});}});});
   if(changed)this.publish(room);
  }
 }
 drop(peer){this.basket.drop(peer);const s=this.states.get(peer.roomId);if(!s)return;s.pads.filter(p=>p.seats.includes(peer.id)).forEach(p=>this.leaveGolf(peer,p,false));s.pp.forEach((p,tb)=>p.seats.forEach((id,side)=>{if(id===peer.id){p.seats[side]=null;p.busy=false;const r=this.rooms.get(peer.roomId);if(r)this.broadcast(r,{t:'pp',k:'stand',tb,side,id});}}));}
}
